### ISSUE TITLE
configure: error: library 'crypto' is required for OpenSSL

### ISSUE THREAD

**Issue by scottrobertson** [smashedtoatoms/asdf-postgres#52]
Trying to install this on macOS 12.3 Beta 2. Getting the following:

```
/Users/scottrobertson/.asdf/plugins/postgres/bin/install: line 45: uconv: command not found
ls: /opt/openssl@*: No such file or directory
Building with options: --prefix=/Users/scottrobertson/.asdf/installs/postgres/11.5     --with-uuid=e2fs     --with-openssl     --with-zlib     --with-libraries='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/lib:/opt/openssl/lib:/lib:/openssl/lib:/libressl/lib:/lib:/usr/local/lib:/usr/lib'     --with-includes='/opt/local/lib:/sw/lib:/usr/local/opt/openssl/include:/opt/openssl/include:/opt/homebrew/include:/include:/openssl/include:/libressl/include:/include:/usr/local/include:/usr/local/lib:/usr/lib'
checking build system type... arm-apple-darwin21.4.0
checking host system type... arm-apple-darwin21.4.0
checking which template to use... darwin
checking whether NLS is wanted... no
checking for default port number... 5432
checking for block size... 8kB
checking for segment size... 1GB
checking for WAL block size... 8kB
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gawk... gawk
checking whether gcc supports -Wdeclaration-after-statement, for CFLAGS... yes
checking whether gcc supports -Wendif-labels, for CFLAGS... yes
checking whether g++ supports -Wendif-labels, for CXXFLAGS... yes
checking whether gcc supports -Wmissing-format-attribute, for CFLAGS... yes
checking whether g++ supports -Wmissing-format-attribute, for CXXFLAGS... yes
checking whether gcc supports -Wformat-security, for CFLAGS... yes
checking whether g++ supports -Wformat-security, for CXXFLAGS... yes
checking whether gcc supports -fno-strict-aliasing, for CFLAGS... yes
checking whether g++ supports -fno-strict-aliasing, for CXXFLAGS... yes
checking whether gcc supports -fwrapv, for CFLAGS... yes
checking whether g++ supports -fwrapv, for CXXFLAGS... yes
checking whether gcc supports -fexcess-precision=standard, for CFLAGS... no
checking whether g++ supports -fexcess-precision=standard, for CXXFLAGS... no
checking whether gcc supports -funroll-loops, for CFLAGS_VECTOR... yes
checking whether gcc supports -ftree-vectorize, for CFLAGS_VECTOR... yes
checking whether gcc supports -Wunused-command-line-argument, for NOT_THE_CFLAGS... yes
checking whether gcc supports -Wformat-truncation, for NOT_THE_CFLAGS... no
checking whether gcc supports -Wstringop-truncation, for NOT_THE_CFLAGS... no
checking whether the C compiler still works... yes
checking how to run the C preprocessor... gcc -E
configure: WARNING: *** Include directory '/opt/local/lib does not exist.
configure: WARNING: *** Include directory /sw/lib does not exist.
configure: WARNING: *** Include directory /usr/local/opt/openssl/include does not exist.
configure: WARNING: *** Include directory /opt/openssl/include does not exist.
configure: WARNING: *** Include directory /include does not exist.
configure: WARNING: *** Include directory /openssl/include does not exist.
configure: WARNING: *** Include directory /libressl/include does not exist.
configure: WARNING: *** Include directory /include does not exist.
configure: WARNING: *** Include directory /usr/local/include does not exist.
configure: WARNING: *** Include directory /usr/lib' does not exist.
configure: WARNING: *** Library directory '/opt/local/lib does not exist.
configure: WARNING: *** Library directory /sw/lib does not exist.
configure: WARNING: *** Library directory /usr/local/opt/openssl/lib does not exist.
configure: WARNING: *** Library directory /opt/openssl/lib does not exist.
configure: WARNING: *** Library directory /lib does not exist.
configure: WARNING: *** Library directory /openssl/lib does not exist.
configure: WARNING: *** Library directory /libressl/lib does not exist.
configure: WARNING: *** Library directory /lib does not exist.
configure: WARNING: *** Library directory /usr/lib' does not exist.
checking allow thread-safe client libraries... yes
checking whether to build with ICU support... no
checking whether to build with Tcl... no
checking whether to build Perl modules... no
checking whether to build Python modules... no
checking whether to build with GSSAPI support... no
checking whether to build with PAM support... no
checking whether to build with BSD Authentication support... no
checking whether to build with LDAP support... no
checking whether to build with Bonjour support... no
checking whether to build with OpenSSL support... yes
checking whether to build with SELinux support... no
checking whether to build with systemd support... no
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ld used by GCC... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for ranlib... ranlib
checking for strip... strip
checking whether it is possible to strip libraries... yes
checking for ar... ar
checking for a BSD-compatible install... /opt/homebrew/bin/ginstall -c
checking for tar... /usr/bin/tar
checking whether ln -s works... yes
checking for a thread-safe mkdir -p... /opt/homebrew/bin/gmkdir -p
checking for bison... /usr/bin/bison
configure: using bison (GNU Bison) 2.3
checking for flex... /usr/bin/flex
configure: using flex 2.6.4 Apple(flex-34)
checking for perl... /usr/bin/perl
configure: using perl 5.30.3
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking if compiler needs certain flags to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_REENTRANT
checking for PTHREAD_PRIO_INHERIT... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for strerror_r... yes
checking for getpwuid_r... yes
checking for gethostbyname_r... no
checking whether strerror_r returns int... yes
checking for main in -lm... yes
checking for library containing setproctitle... no
checking for library containing dlopen... none required
checking for library containing socket... none required
checking for library containing shl_load... no
checking for library containing getopt_long... none required
checking for library containing crypt... none required
checking for library containing shm_open... none required
checking for library containing shm_unlink... none required
checking for library containing clock_gettime... none required
checking for library containing fdatasync... none required
checking for library containing sched_yield... none required
checking for library containing gethostbyname_r... no
checking for library containing shmget... none required
checking for library containing readline... -lreadline
checking for inflate in -lz... yes
checking for CRYPTO_new_ex_data in -lcrypto... no
configure: error: library 'crypto' is required for OpenSSL
```

Note, I have ran `brew install gcc readline zlib curl ossp-uuid` as well as also trying `brew install openssl`

asdf v0.9.0

**Comment by smashedtoatoms** [comment]
Does installing crypto make it work?  I seriously want to pour hot coffee on the children of the devs at Apple who have made OpenSSL this much of a pain in the ass. I'm kidding... probably. 

I don't have 12.3 beta 2 installed and likely won't be able to because the only machine I have to do it on is my work one. I'll see if I can figure out where it's moved. 

In the meantime, you might try to see if you can find libcrypto and libssl and symlink them for now. Something like this might shake ur loose, but it's a hack. If you can't find libssl or libcrypto, try to install those first. If any of that works let me know so I can update the docs. 

```sh
sudo ln -s /opt/homebrew/opt/openssl/lib/libcrypto.dylib /opt/local/lib/
sudo ln -s /opt/homebrew/opt/openssl/lib/libssl.dylib /opt/local/lib/
```

**Comment by scottrobertson** [comment]
Ha... yeah it's a nightmare. 

How would I install `crypto`?

And I have run both of those symlinks, and they success, but still seeing the same error sadly.

**Comment by scottrobertson** [comment]
So, this comment got me further, but now I am seeing: 

https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7?permalink_comment_id=3810046#gistcomment-3810046

```
configure: error: header file <openssl/ssl.h> is required for OpenSSL
```

**Comment by smashedtoatoms** [comment]
Yea, so now you need to do whatever you did for `libcrypto` for `libssl`.  Which step moved the error for you?  This problem always comes in pairs because they're both installed with openssl, but Apple keeps moving shit around.

**Comment by scottrobertson** [comment]
Thank you. I think we will carry on for now and get this merged into our dev env (we are replacing Docker with this setup), and see how it goes. Others (some on M1, some on intel) have not had issues yet, but we will see as 12.3 becomes more common/stable.

**Comment by smashedtoatoms** [comment]
Let me know if it causes problems and I'll get it sorted.  It's definitely easier to track down if it happens more often or if I can make it happen directly.

**Comment by smashedtoatoms** [comment]
Also, I love that you're using this in place of docker.  That is literally why I originally did it.  Let me know how I can help.

**Comment by scottrobertson** [comment]
Just had 1 more dev hit this issue. Still trying to determine why most don't see it, but some do.

**Comment by scottrobertson** [comment]
May be worth looking at asdf-ruby. They seem to install openssl every time I do a new version install. Or it may be ruby-build doing it.

**Comment by smashedtoatoms** [comment]
I tried to rip it off once before but ran out of time.  I will see if I can take another stab at it one of these weekends.  I long for the day when all that is openssl gets its shit together.  I spend a lot more time than anyone should have to on compiler toolchains that would just work if it weren't for the trainwreck that is shared libraries involving openssl.

**Comment by tino415** [comment]
Today I also hit this error today and definining environmental variable `HOMEBREW_PREFIX` to `/opt/homebrew` fixed it for me.

**Comment by timriley** [comment]
Completely fresh macOS (12.13.1) and Homebrew install here, and along with the necessary `brew install gcc readline zlib curl ossp-uuid` step from the README, @tino415's `HOMEBREW_PREFIX=/opt/homebrew` is what fixed postgres installation for me.

**Comment by smashedtoatoms** [comment]
Sorry all, my Github notifications are failing.  I updated the readme to capture this.  Thanks, @tino415 for figuring it out and @timriley for confirming it.

**Comment by ThePJMP** [comment]
@smashedtoatoms worth mentioning HOMEBREW_PREFIX depends on wheter the computer is Intel or Silicon processor. Problem was solved for me when I set `HOMEBREW_PREFIX=/usr/local/`. Prefix is mentioned on [Homebrew Docs](https://docs.brew.sh/Installation)

**Comment by smashedtoatoms** [comment]
Makes sense.  This is always going to be dependent on where crypto is located.  I updated the docs.

**Comment by Qqwy** [comment]
This situation is still not perfect.
Even though `HOMEBREW_PREFIX` was set to the correct path on my new macbook (running Ventura), I still had to follow [the steps from @smashedtoatoms' comment above](https://github.com/smashedtoatoms/asdf-postgres/issues/52#issuecomment-1033794237) for it to find `crypto`. 

Fully replacing the LDFLAGS and CPPFLAGS works 'fine' for installing this particular asdf command right now, as long as you close the shell afterwards. If you want to install other programs you might need other extensions to library paths. So you might prefer e.g.

```
brew install openssl
export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib $LDFLAGS"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include $CPPFLAGS"
```

instead.

**Comment by smashedtoatoms** [comment]
Yea, this is the hellscape we all have to deal with, unfortunately.  As long as this isn't tied to a specific solution, or I don't write a spaghetti monster of conditional config, this will be how it is.  If it were more general purpose, it would keep me up at night, but for me, it is a developer tool, and the assumptions made about the user are set accordingly.  If I can think of a way to make this more predictable, I will implement it.  Sorry this is such a pain.

**Comment by pythoninthegrass** [comment]
Came here for the `crypto` error. Was testing @Qqwy's exports and they worked for 15.5 but not 16.1; was getting 
```
checking for icu-uc icu-i18n... no
configure: error: ICU library not found
If you have ICU already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-icu to disable ICU support.
```

Latter has new [bison dependencies](https://stackoverflow.com/questions/76477533/installing-age-pg16-beside-postgresql-v16beta1-giving-bison-is-missing-while-it) apparently. Based on this [thread](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-macOS-using-CMake#problem-5-cmake-cannot-find-the-required-icu-library), solved it via
```bash
brew install gcc icu4c readline zlib curl ossp-uuid pkg-config
asdf plugin-add postgres
export OPENSSL_PATH=$(brew --prefix openssl)
export CMAKE_PREFIX_PATH=$(brew --prefix icu4c)
export PATH="$OPENSSL_PATH/bin:$CMAKE_PREFIX_PATH/bin:$PATH"
export LDFLAGS="-L$OPENSSL_PATH/lib $LDFLAGS"
export CPPFLAGS="-I$OPENSSL_PATH/include $CPPFLAGS"
export PKG_CONFIG_PATH="$CMAKE_PREFIX_PATH/lib/pkgconfig"
asdf list-all postgres
asdf install postgres 16.1
```
